name: ExamplePlugin
version: '2.0.1'
main: org.rendang.plugin.example.ExamplePlugin
api-version: '1.21'
commands:
    example:
        description: Example command
        usage: /example help
        aliases:
        - ex